// KenLED animation: sample-blink
// Sample placeholder so the sketch compiles out of the box — replace this
// file with an export from the KenLED designer app.
// Generated by the KenLED designer. Grid is row-major, origin top-left.
// Drop this file next to kenled.ino and flash.
#pragma once
#include <stdint.h>

#define ANIM_COLS 8
#define ANIM_ROWS 10
#define ANIM_NUM_LEDS 80
#define ANIM_FRAME_COUNT 2
#define ANIM_FRAME_MS 500

// 16-color palette, 0xRRGGBB. Index 0 is "off".
static const uint32_t ANIM_PALETTE[16] = {
  0x000000, 0xFFFFFF, 0xFF3B30, 0xFF9500, 0xFFCC00, 0x34C759, 0x00C7BE, 0x32ADE6, 0x007AFF, 0x5856D6, 0xAF52DE, 0xFF2D95, 0x8E2500, 0x146B2E, 0x8E8E93, 0x3A3A3C
};

// Palette indices per pixel, one row of the grid per source line.
static const uint8_t ANIM_FRAMES[ANIM_FRAME_COUNT][ANIM_NUM_LEDS] = {
  { 0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0 },
  { 2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2,
    2,2,2,2,2,2,2,2 }
};
