import type { Design } from './types.ts'

/** Render a design as a C header for the firmware sketch (firmware/kenled). */
export function designToHeader(design: Design): string {
  const { name, cols, rows, frameDurationMs, palette, frames } = design
  const numLeds = cols * rows

  const paletteLines = palette.map((hex) => `0x${hex.slice(1).toUpperCase()}`).join(', ')
  const frameLines = frames
    .map((frame) => {
      const bytesPerRow: string[] = []
      for (let y = 0; y < rows; y++) {
        bytesPerRow.push(frame.slice(y * cols, (y + 1) * cols).join(','))
      }
      return `  { ${bytesPerRow.join(',\n    ')} }`
    })
    .join(',\n')

  return `// KenLED animation: ${name.replace(/[^\x20-\x7e]/g, '') || 'untitled'}
// Generated by the KenLED designer. Grid is row-major, origin top-left.
// Drop this file next to kenled.ino and flash.
#pragma once
#include <stdint.h>

#define ANIM_COLS ${cols}
#define ANIM_ROWS ${rows}
#define ANIM_NUM_LEDS ${numLeds}
#define ANIM_FRAME_COUNT ${frames.length}
#define ANIM_FRAME_MS ${frameDurationMs}

// 16-color palette, 0xRRGGBB. Index 0 is "off".
static const uint32_t ANIM_PALETTE[16] = {
  ${paletteLines}
};

// Palette indices per pixel, one row of the grid per source line.
static const uint8_t ANIM_FRAMES[ANIM_FRAME_COUNT][ANIM_NUM_LEDS] = {
${frameLines}
};
`
}
